- name: apache install
  yum: name=httpd state=present

- name: apache start at server boot
  service: name=httpd state=started enabled=yes

- name: apache listen in all interfaces on port 80
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " line="Listen *:{{ http_port }} " state=present
  notify:
    - restart httpd